[project]
name = "monitoring"
version = "1.0"
requires-python = ">=3.12,<3.14" # T408108
dependencies = [
    "click",
    "requests",
    "fastapi[standard]",
    "PyYaml",
]

[tool.poetry.build]
generate-setup-file = false
script = "setup.py"
