groups:
  - name: ClueBot NG
    rules:
      - alert: BotNotEditedRecently
        expr: time() - cbng_monitoring_last_user_contribution_time{username="ClueBot NG", domain="en.wikipedia.org"} > 3600
        for: 5m
        labels:
          update_wiki_host: en.wikipedia.org
          update_wiki_page: User:ClueBot_NG/running
        annotations:
          summary: ClueBot NG has not edited for > 1 hour

      - alert: BotHasLowEditCount
        expr: cbng_monitoring_recent_user_contributions_count{username="ClueBot NG", domain="en.wikipedia.org"} < 20000
        for: 5m
        annotations:
          summary: ClueBot NG has made less than 20k edits in the last 24 hours

      - alert: BotHasBeenAdminDisabled
        expr: cbng_monitoring_bot_administrator_allow_run{username="ClueBot NG", domain="en.wikipedia.org"} == 0
        for: 5m
        annotations:
          summary: ClueBot NG has been disabled via User:ClueBot_NG/Run
