name: Deploy
on: { push: { tags: [ 'v*' ] } }
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: cluebotng/ci-update-component-ref@main
        with:
          tool: 'cluebotng-monitoring'
          component: 'prometheus'
          ref: '${{ github.ref }}'
          gh_app_key: '${{ secrets.CI_COMPONENT_CONFIGS_APP_KEY }}'

  webservice:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cluebotng/ci-execute-fabric@main
        with:
          task: setup-webservice
          ssh_key: ${{ secrets.CI_SSH_KEY }}
